### ISSUE TITLE
Add U+2261 "≡"

### ISSUE THREAD

**Issue by dvn0** [arp242/uni#13]
The [triple bar](https://en.wikipedia.org/wiki/Triple_bar) appears to be missing from the unicode db.

**Comment by arp242** [comment]
It seems to work:

    $ uni p u+2261
         cpoint  dec    utf-8       html       name
    '≡'  U+2261  8801   e2 89 a1    &equiv;    IDENTICAL TO (Math_Symbol)

Why do you think it's missing?

**Comment by dvn0** [comment]
Oh, it's because the name isn't "triple bar". Also I didn't search the u+2261 the correct way... oops!

Thanks.

**Comment by arp242** [comment]
Yeah, some names are perhaps a bit unintuitive and inconsistent. Sometimes, they're semantic (like "identical to"), other times they're descriptive (like "leftwards arrow").

As far as I can find, Unicode doesn't maintain list of aliases for this; the CLDR (#11) only has them for emojis.

> Also I didn't search the u+2261 the correct way... oops!

How did you search for it?
