### ISSUE TITLE
Add a -v (version) flag

### ISSUE THREAD

**Issue by StevenBlack** [arp242/uni#19]
Hi Martin,

I stumbled upon Uni again, after using it quite awhile ago.  I was thinking, *I wonder if that's been updated?*

But `uni -v` just returns standard help, and not a release or version number, as per convention.

So this issue serves to say, `-v` is useful to users who come back to `uni` after moderate period of time.

I may submit a PR for this, but just leaving this here in the meantime.  *Proost!*

**Comment by arp242** [comment]
To be honest I just hate maintaining this: I always forget to update it, or it complicates the build process. It's always an annoyance. I'd rather not add it.

**Comment by arp242** [comment]
Okay, I changed my mind and added it anyway:

    [~c/uni](master)% ./dist/uni-v1.9.9-linux-amd64 version
    v1.9.9 63a89db 2020-10-19

`uni -v`, `uni -version`, `uni --version`, `uni version` all works.

Maybe I was a bit too grumpy the other day 😅

**Comment by StevenBlack** [comment]
That's cool Martin.  I hear you.  I feel likewise on some (most?) days in my active public repos.

I just want to let you know, I ❤️ uni!
