### ISSUE TITLE
FZF integration

### ISSUE THREAD

**Issue by Seirdy** [arp242/uni#2]
Adding an integration to FZF could make this tool replace [emoji-fzf](https://github.com/noahp/emoji-fzf). I'm up for implementing this and opening a PR after exams finish.

**Comment by arp242** [comment]
Sounds good as long as it's not too complex (judging from that link, it works similar to dmenu/rofi by just filtering stdin?) If it does turn out to be very complex it's probably best off in its own repo.

**Comment by rolandwalker** [comment]
It just filters stdin, so in brief
```sh
#!/bin/sh
uni -q emoji "${*:-all}" | fzf | cut -c1
```

**Comment by arp242** [comment]
Looks good! Send a patch and I'll merge it.
