### ISSUE TITLE
Thank you! + new integration

### ISSUE THREAD

**Issue by adamkiss** [arp242/uni#38]
With MacOS Ventura, the python 2 is gone! And instead of installing the extremely outdated python2, I looked for a replacement for my trusty old `utf` workflow.

`uni` (with a bit of `jq` magic) is exactly what I needed, so thank you 💖

Link for integration: https://github.com/adamkiss/alfred-uni

**Comment by arp242** [comment]
Cheers, I can add a note about it in the README, but I'm not entirely sure what "Alfred" is? Is that a built-in macOS thing or another application?

**Comment by adamkiss** [comment]
@arp242 Alfred is a very very old & solid app - a Spotlight alternative/replacement back from the times when Spotlight was a little less than a file search - https://www.alfredapp.com. One of its main features - aside from snippets, clipboard history and more - is a support for custom workflows.

**Comment by adamkiss** [comment]
I've did a separate utf workflow for alfred launcher, though I did use uni to build  the database heavily, so thank you again 😀 

Closing for now, but i might do full uni integration into alfred in the future.
