### ISSUE TITLE
Zip with Windows release

### ISSUE THREAD

**Issue by cup** [arp242/uni#5]
I see here

https://github.com/arp242/uni/releases

that all releases are GZ, even Windows. This isnt a huge deal, as you can get
tools to extract GZ on Windows. However to my knowledge they arent built in,
even with Windows 10.

So it might make sense to offer ZIP builds instead to Windows users.

**Comment by arp242** [comment]
I agree zip would be better, but it's a bit difficult to integrate in the current build script.

I'd argue that the target audience for this tool will know how to `gzip -d` a file (or use 7zip, or some other tool).

I'm closing this for now as a "won't fix", as the time I need to spend on fixing this isn't really a good ROI, IMHO. But I appreciate the feedback!

**Comment by cup4** [comment]
https://devblogs.microsoft.com/commandline/tar-and-curl-come-to-windows
