### ISSUE TITLE
Homebre Formula

### ISSUE THREAD

**Issue by andres-lowrie** [arp242/uni#6]
Would be neat to have a Hombrew Formula for this tool. https://github.com/homebrew/brew/

I could contribute this if you like

**Comment by arp242** [comment]
As I understand it, this is something that should be added to the homebrew repo, rather than in this repo? At least, that's the impression I have from glancing at [the docs](https://docs.brew.sh/Formula-Cookbook).

**Comment by andres-lowrie** [comment]
my bad, sorry about that 😊

**Comment by arp242** [comment]
I released version 1.1 FYI @andres-lowrie
